// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bpqwglqfybzoaedfarma.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJwcXdnbHFmeWJ6b2FlZGZhcm1hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1NjI1MTAsImV4cCI6MjA3MDEzODUxMH0.HA-QIca1IcqU8KsTaONH1zZk7uJidcHCrcuYEN6yVkQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});